import { fromSources } from '../../shared/code-viewer/code-snippet';
import { SOURCES } from './sources.generated';

export const SNIPPETS = fromSources(SOURCES, [
  ['ai-code-analyzer.ts', 'Each rule is a small, tested pure function.'],
  ['CLAUDE.md (generated by --ai-config)', 'The rules file this very project was generated with.'],
  '.mcp.json',
  'review-ai-code.page.ts',
]);
