// Generates `sources.generated.ts` next to every video demo so the "Code" tab shows the
// exact source files that are running – no hand-copied snippets that can drift.
// Also generates `src/app/core/generated/build-info.generated.ts` (budgets, versions) for video 023.
import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const videosDir = join(root, 'src', 'app', 'videos');
const SOURCE_EXT = /\.(ts|html|scss)$/;
const SKIP = /(\.spec\.ts|\.generated\.ts|\.snippets\.ts)$/;

function walk(dir) {
  return readdirSync(dir).flatMap((name) => {
    const full = join(dir, name);
    return statSync(full).isDirectory() ? walk(full) : [full];
  });
}

function write(file, content) {
  const previous = existsSync(file) ? readFileSync(file, 'utf8') : '';
  if (previous !== content) {
    writeFileSync(file, content);
    return true;
  }
  return false;
}

const header = '// AUTO-GENERATED by scripts/generate-sources.mjs – do not edit.\n';
let changed = 0;

for (const folder of readdirSync(videosDir)) {
  const dir = join(videosDir, folder);
  if (!statSync(dir).isDirectory()) continue;
  const manifestPath = join(dir, 'sources.json');
  const manifest = existsSync(manifestPath) ? JSON.parse(readFileSync(manifestPath, 'utf8')) : {};
  const files = walk(dir)
    .filter((f) => SOURCE_EXT.test(f))
    .filter((f) => !SKIP.test(f) || (manifest.includeSpecs && f.endsWith('.spec.ts')))
    .sort();
  const entries = files.map((f) => [
    relative(dir, f).split(sep).join('/'),
    readFileSync(f, 'utf8'),
  ]);
  for (const [label, path] of Object.entries(manifest.extra ?? {})) {
    const full = resolve(dir, path);
    let text = readFileSync(full, 'utf8');
    const jsonPick = manifest.jsonPick?.[label];
    if (jsonPick) {
      let value = JSON.parse(text);
      for (const key of jsonPick) value = value[key];
      text = JSON.stringify(value, null, 2) + '\n';
    }
    entries.push([label, text]);
  }
  const body = entries
    .map(([name, text]) => `  ${JSON.stringify(name)}: ${JSON.stringify(text)},`)
    .join('\n');
  const out = `${header}export const SOURCES: Readonly<Record<string, string>> = {\n${body}\n};\n`;
  if (write(join(dir, 'sources.generated.ts'), out)) changed++;
}

const angularJson = JSON.parse(readFileSync(join(root, 'angular.json'), 'utf8'));
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
const project = Object.values(angularJson.projects)[0];
const budgets = project.architect.build.configurations.production.budgets ?? [];
const genDir = join(root, 'src', 'app', 'core', 'generated');
mkdirSync(genDir, { recursive: true });
const buildInfo = `${header}export interface BudgetInfo {
  readonly type: string;
  readonly maximumWarning?: string;
  readonly maximumError?: string;
}

export const BUILD_INFO = {
  angularVersion: ${JSON.stringify(pkg.dependencies['@angular/core'])},
  materialVersion: ${JSON.stringify(pkg.dependencies['@angular/material'])},
  budgets: ${JSON.stringify(budgets, null, 2).replace(/\n/g, '\n  ')} as readonly BudgetInfo[],
  scripts: ${JSON.stringify(pkg.scripts, null, 2).replace(/\n/g, '\n  ')} as Readonly<Record<string, string>>,
} as const;
`;
if (write(join(genDir, 'build-info.generated.ts'), buildInfo)) changed++;
console.log(`[snippets] generated sources (${changed} file(s) updated)`);
